var first_name="Ranbir";
var last_name="Kapoor";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add=a+b;
var  subtract=a-b;
var multiply=a*b;
var divide=a/b;
console.log(add);
console.log(subtract);
console.log(multiply);
console.log(divide);